development:
  adapter: mysql
  database: sample_app_dev
  username: developer 
  password: developer 
  host: localhost
test:
  adapter: mysql
  database: sample_app_test
  username: developer 
  password: developer 
  host: localhost
production:
  adapter: mysql
  database: sample_app_prod
  username: developer 
  password: developer 
  host: localhost
