development:
  adapter: mysql
  database: sample_app_dev
  username: developer 
  password: developer 
  host: localhost
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: sample_app_test
  username: developer 
  password: developer 
  host: localhost
  socket: /tmp/mysql.sock
  
production:
  adapter: postgres
  database: sample_app_prod
  username: ghbhxvbjas
  password: PuzCVZWvdcOZmkhA1WMY 
